name: flutter_chen_common
description: "A Flutter Common package For Helper and Widgets."
version: 1.1.3
homepage: https://github.com/Er-Dong-Chen/flutter-common

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.0.0                           # GetX
  dio: ^5.0.0                           # 网络请求
  cookie_jar: ^4.0.0                    # 缓存jar
  dio_cookie_manager: ^3.0.0            # 请求缓存
  shared_preferences: ^2.0.0            # 本地缓存
  permission_handler: ^11.0.0           # 权限获取
  logger: ">=1.0.0 <5.0.0"              # 日志打印
  pull_to_refresh: ^2.0.0               # 刷新
  flutter_staggered_grid_view: ^0.7.0   # 瀑布流
  bot_toast: ^4.0.0                     # 消息提示
  crypto: ^3.0.0                        # 加密

  # 图片
  image_picker: ^1.0.0                  # 图片选择
  photo_view: ^0.14.0                   # 图片预览
  cached_network_image: ^3.0.0          # 图片缓存
  image_gallery_saver: ^2.0.0           # 图片保存
  image_cropper: ">=4.0.0 <6.0.0"       # 图片裁剪
  multi_image_picker_view: ^1.0.0       # 图片选择
  card_swiper : ^3.0.0                  # 图片轮播

  # 版本更新
  package_info_plus: ^5.0.0             # App信息
  path_provider: ^2.0.0                 # 文件路径
  ota_update: ^6.0.0                    # App下载
  open_file: ^3.0.0                     # 打开文件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
#   assets:
#     - assets/
#     - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
